name: Run Automation Script

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"  # Runs every 6 hours
    
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - uses: actions/checkout@v4

      # 2. Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run your script with custom arguments
      - name: Run script
        run: npm run dev -- --threshold
        env:
          SRP_METAMASK: ${{ secrets.SRP_METAMASK }}
          SRP_KRAKEN: ${{ secrets.SRP_KRAKEN }}
          ADDRESS_KRAKEN: ${{ secrets.ADDRESS_KRAKEN }}
